default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  host: db  # ✅ This must match the service name in docker-compose.yml

development:
  <<: *default
  database: rails_dev

test:
  <<: *default
  database: rails_test

production:
  <<: *default
  database: rails_prod
